server:
  port: 8081

spring:
  h2:
    consol:
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:h2:file:~/appdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      cache-null-values: true
