server:
  port: 8081

spring:
  h2:
    consol:
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:h2:file:~/appdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  cache:
    type: redis # no need to set type if there is only one cache service is added
    redis:
      host: localhost
      port: 6379
      cache-null-values: true
      time-to-live: 86400 # 24 hours
